import type { PropertyType, RoomType } from '../schemas';

export interface RoomTemplate {
  room_type: RoomType;
  default_label: string;
  photo_hints: string[];
}

/** Suggested photo checklist items per room type (static UI hints) */
export const ROOM_PHOTO_HINTS: Record<RoomType, string[]> = {
  kitchen: [
    'Countertops',
    'Sink & faucet',
    'Stove/oven',
    'Refrigerator (inside & outside)',
    'Dishwasher',
    'Cabinets & drawers',
    'Floor',
    'Ceiling',
    'Walls',
    'Light fixtures',
    'Backsplash',
    'Windows',
  ],
  bathroom: [
    'Toilet',
    'Sink & vanity',
    'Bathtub / shower',
    'Shower door/curtain rod',
    'Mirror',
    'Cabinets',
    'Floor & tiles',
    'Ceiling (check for mold)',
    'Walls',
    'Exhaust fan',
    'Towel bars/hooks',
  ],
  bedroom: [
    'Walls (all 4)',
    'Ceiling',
    'Floor / carpet',
    'Closet (inside)',
    'Windows & blinds',
    'Light fixtures',
    'Outlets & switches',
    'Door & doorframe',
  ],
  living_room: [
    'Walls (all 4)',
    'Ceiling',
    'Floor / carpet',
    'Windows & blinds',
    'Light fixtures',
    'Outlets & switches',
    'Fireplace (if present)',
    'Built-in shelves',
  ],
  dining_room: [
    'Walls',
    'Ceiling',
    'Floor',
    'Light fixture / chandelier',
    'Windows',
    'Built-in features',
  ],
  entry: [
    'Front door (inside & outside)',
    'Door lock & deadbolt',
    'Floor / mat area',
    'Walls',
    'Coat closet',
    'Light fixture',
    'Doorbell / intercom',
  ],
  hallway: ['Walls', 'Ceiling', 'Floor', 'Light fixtures', 'Smoke detectors'],
  closet: [
    'Shelving',
    'Rod & hangers',
    'Floor',
    'Walls',
    'Light (if present)',
    'Door & track',
  ],
  garage: [
    'Garage door (inside & outside)',
    'Floor (oil stains, cracks)',
    'Walls',
    'Ceiling',
    'Light fixtures',
    'Outlets',
    'Storage areas',
  ],
  patio: [
    'Surface / decking',
    'Railings',
    'Walls / fencing',
    'Light fixtures',
    'Sliding door / screen',
    'Drainage',
  ],
  balcony: [
    'Surface / floor',
    'Railings',
    'Ceiling (if covered)',
    'Sliding door / screen',
    'Light fixtures',
  ],
  laundry: [
    'Washer connections',
    'Dryer vent',
    'Floor',
    'Walls',
    'Shelving',
    'Sink (if present)',
    'Light fixture',
  ],
  basement: [
    'Walls (check for moisture)',
    'Floor',
    'Ceiling / exposed pipes',
    'Windows',
    'Sump pump (if present)',
    'Water heater',
    'HVAC equipment',
  ],
  attic: [
    'Access point / stairs',
    'Insulation',
    'Roof underside',
    'Ventilation',
    'Floor / joists',
  ],
  office: [
    'Walls',
    'Ceiling',
    'Floor',
    'Windows & blinds',
    'Light fixtures',
    'Outlets & data jacks',
    'Door',
  ],
  other: ['Walls', 'Ceiling', 'Floor', 'Light fixtures', 'Windows', 'Any notable features'],
};

/** Default room templates per property type */
export const PROPERTY_ROOM_TEMPLATES: Record<PropertyType, RoomTemplate[]> = {
  apartment: [
    { room_type: 'entry', default_label: 'Entry', photo_hints: ROOM_PHOTO_HINTS.entry },
    { room_type: 'living_room', default_label: 'Living Room', photo_hints: ROOM_PHOTO_HINTS.living_room },
    { room_type: 'kitchen', default_label: 'Kitchen', photo_hints: ROOM_PHOTO_HINTS.kitchen },
    { room_type: 'bedroom', default_label: 'Bedroom', photo_hints: ROOM_PHOTO_HINTS.bedroom },
    { room_type: 'bathroom', default_label: 'Bathroom', photo_hints: ROOM_PHOTO_HINTS.bathroom },
    { room_type: 'closet', default_label: 'Closet', photo_hints: ROOM_PHOTO_HINTS.closet },
  ],
  studio: [
    { room_type: 'entry', default_label: 'Entry', photo_hints: ROOM_PHOTO_HINTS.entry },
    { room_type: 'living_room', default_label: 'Main Living Area', photo_hints: ROOM_PHOTO_HINTS.living_room },
    { room_type: 'kitchen', default_label: 'Kitchen', photo_hints: ROOM_PHOTO_HINTS.kitchen },
    { room_type: 'bathroom', default_label: 'Bathroom', photo_hints: ROOM_PHOTO_HINTS.bathroom },
    { room_type: 'closet', default_label: 'Closet', photo_hints: ROOM_PHOTO_HINTS.closet },
  ],
  condo: [
    { room_type: 'entry', default_label: 'Entry', photo_hints: ROOM_PHOTO_HINTS.entry },
    { room_type: 'living_room', default_label: 'Living Room', photo_hints: ROOM_PHOTO_HINTS.living_room },
    { room_type: 'kitchen', default_label: 'Kitchen', photo_hints: ROOM_PHOTO_HINTS.kitchen },
    { room_type: 'dining_room', default_label: 'Dining Room', photo_hints: ROOM_PHOTO_HINTS.dining_room },
    { room_type: 'bedroom', default_label: 'Master Bedroom', photo_hints: ROOM_PHOTO_HINTS.bedroom },
    { room_type: 'bedroom', default_label: 'Bedroom 2', photo_hints: ROOM_PHOTO_HINTS.bedroom },
    { room_type: 'bathroom', default_label: 'Bathroom', photo_hints: ROOM_PHOTO_HINTS.bathroom },
    { room_type: 'balcony', default_label: 'Balcony', photo_hints: ROOM_PHOTO_HINTS.balcony },
    { room_type: 'laundry', default_label: 'Laundry', photo_hints: ROOM_PHOTO_HINTS.laundry },
  ],
  house: [
    { room_type: 'entry', default_label: 'Entry', photo_hints: ROOM_PHOTO_HINTS.entry },
    { room_type: 'living_room', default_label: 'Living Room', photo_hints: ROOM_PHOTO_HINTS.living_room },
    { room_type: 'kitchen', default_label: 'Kitchen', photo_hints: ROOM_PHOTO_HINTS.kitchen },
    { room_type: 'dining_room', default_label: 'Dining Room', photo_hints: ROOM_PHOTO_HINTS.dining_room },
    { room_type: 'bedroom', default_label: 'Master Bedroom', photo_hints: ROOM_PHOTO_HINTS.bedroom },
    { room_type: 'bedroom', default_label: 'Bedroom 2', photo_hints: ROOM_PHOTO_HINTS.bedroom },
    { room_type: 'bedroom', default_label: 'Bedroom 3', photo_hints: ROOM_PHOTO_HINTS.bedroom },
    { room_type: 'bathroom', default_label: 'Master Bathroom', photo_hints: ROOM_PHOTO_HINTS.bathroom },
    { room_type: 'bathroom', default_label: 'Bathroom 2', photo_hints: ROOM_PHOTO_HINTS.bathroom },
    { room_type: 'garage', default_label: 'Garage', photo_hints: ROOM_PHOTO_HINTS.garage },
    { room_type: 'patio', default_label: 'Patio / Yard', photo_hints: ROOM_PHOTO_HINTS.patio },
    { room_type: 'laundry', default_label: 'Laundry Room', photo_hints: ROOM_PHOTO_HINTS.laundry },
    { room_type: 'basement', default_label: 'Basement', photo_hints: ROOM_PHOTO_HINTS.basement },
  ],
  townhouse: [
    { room_type: 'entry', default_label: 'Entry', photo_hints: ROOM_PHOTO_HINTS.entry },
    { room_type: 'living_room', default_label: 'Living Room', photo_hints: ROOM_PHOTO_HINTS.living_room },
    { room_type: 'kitchen', default_label: 'Kitchen', photo_hints: ROOM_PHOTO_HINTS.kitchen },
    { room_type: 'dining_room', default_label: 'Dining Room', photo_hints: ROOM_PHOTO_HINTS.dining_room },
    { room_type: 'bedroom', default_label: 'Master Bedroom', photo_hints: ROOM_PHOTO_HINTS.bedroom },
    { room_type: 'bedroom', default_label: 'Bedroom 2', photo_hints: ROOM_PHOTO_HINTS.bedroom },
    { room_type: 'bathroom', default_label: 'Bathroom', photo_hints: ROOM_PHOTO_HINTS.bathroom },
    { room_type: 'bathroom', default_label: 'Bathroom 2', photo_hints: ROOM_PHOTO_HINTS.bathroom },
    { room_type: 'garage', default_label: 'Garage', photo_hints: ROOM_PHOTO_HINTS.garage },
    { room_type: 'patio', default_label: 'Patio', photo_hints: ROOM_PHOTO_HINTS.patio },
    { room_type: 'laundry', default_label: 'Laundry', photo_hints: ROOM_PHOTO_HINTS.laundry },
  ],
  other: [
    { room_type: 'entry', default_label: 'Entry', photo_hints: ROOM_PHOTO_HINTS.entry },
    { room_type: 'living_room', default_label: 'Main Room', photo_hints: ROOM_PHOTO_HINTS.living_room },
    { room_type: 'kitchen', default_label: 'Kitchen', photo_hints: ROOM_PHOTO_HINTS.kitchen },
    { room_type: 'bathroom', default_label: 'Bathroom', photo_hints: ROOM_PHOTO_HINTS.bathroom },
  ],
};

/** All available room types with display labels */
export const ROOM_TYPE_LABELS: Record<RoomType, string> = {
  kitchen: 'Kitchen',
  bathroom: 'Bathroom',
  bedroom: 'Bedroom',
  living_room: 'Living Room',
  dining_room: 'Dining Room',
  entry: 'Entry / Foyer',
  hallway: 'Hallway',
  closet: 'Closet',
  garage: 'Garage',
  patio: 'Patio / Yard',
  balcony: 'Balcony',
  laundry: 'Laundry Room',
  basement: 'Basement',
  attic: 'Attic',
  office: 'Office / Study',
  other: 'Other',
};

/** US State abbreviations */
export const US_STATES = [
  'AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL',
  'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME',
  'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH',
  'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI',
  'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY',
] as const;
